# name: Dependabot Auto Merge

# on:
#   pull_request:

# jobs:
#   auto-merge:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: ahmadnassri/action-dependabot-auto-merge@v2
#         with:
#           target: minor
#           github-token: ${{ secrets.mytoken }}
name: Dependabot Auto Merge
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ...

  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}